Force Delete Final Version for Review
shivsahni/NSBrute pull request #4
Opened 2020-03-12 07:45 UTC by mardinyadegar

A couple things to note here (they are honestly summarized in `README.md` but it might just be easier to put here):

1) I have made this force delete functionality run every time the script is run
2) An optional feature I included allows you include a `-k` or `--zonesToKeep` you can specify a list of Hosted Zone IDs that you do not want to delete and it will avoid those zones when deleting hosted zones

Thanks for your time Shiv, I hope you have a nice day and thanks for letting me work on this with you!
@mardinyadegar

2020-03-20 20:51 UTC, mardinyadegar commented
Also Shiv, just wanted to say, I want to make another switch for auto create PoC. Would you be opposed to reviewing a PR for this functionality?

2020-03-26 14:51 UTC, ehsandeep approved these changes

2020-03-28 03:46 UTC, shivsahni requested changes
Hey Mardin,
Thanks for your contribution.

I see that you are now deleting all the hosted zones except the ones provided through CLI. I was just wondering it might become tedious for users to provide the list of zone IDs they want to keep. I think it would be great if we instead delete the zones that NSBrute created except the one which is meant for POC purpose.

2020-03-28 03:48 UTC, shivsahni commented
Regarding the `switch for auto create PoC`, please feel free to contribute. Let me know if you need any support from my end.

2020-03-28 15:04 UTC, mardinyadegar commented
Sure Shiv, that seems very reasonable. Let me work on a PoC of this and I will submit the code to you.

2020-03-29 02:05 UTC, mardinyadegar commented
Shiv, I opened PR #6 please see this PR and approve that there. I'd like to maintain this version just in case I want to use it for personal reasons.

2020-04-06 14:21 UTC, merged